gripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_1f
    joint_speed: 1.0
    motor:
        id: 1
        init: 1606
        min: 1606
        max: 2616

