neckHead_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neckHead_dynamixel_joint
    joint_speed: 0.5
    port_name: "/dev/usb-ports/1-1.4"
    motor:
        id: 1
        init: 3161
        min: 2200
        max: 4000
    
